config/routes.rb
Rails.application.routes.draw do
  resources :batches
  resources :products
  resources :operations
  resources :routes
  resources :countries
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'main/home', to: 'home#main', as: 'main_home'
  get 'main/about', to: 'home#about', as: 'main_about'

  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h2 class="alert-heading"><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class.name.downcase %>
      from being saved:</h2>
    <ul>
      <% obj.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<% if notice != nil %>
  <div class="row justify-content-md-center">
    <div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert">
      <div class="mt-1 px-3 d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </svg>
        <p style="color: green" class="mx-3 my-2"><%= notice %></p>
      </div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

<% if alert != nil %>
  <div class="row justify-content-md-center">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <div class="mt-1 px-3 d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </svg>
        <p class="mx-3 my-2"><%= alert %></p>
      </div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav
  class="navbar navbar-expand-lg navbar-light bg-light sticky-top shadow-sm"
>
  <div class="container-fluid d-flex">
    <div class="col-6 d-flex align-items-center">
      <a class="navbar-brand" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
        <%= image_tag("logo-navbar.svg", :alt => "logo-navbar", :width => "60") %>
      </a>
      <p class="mt-3" style="font-size: 1.4rem">Bienvenido a Skynet</p>
    </div>

    <div class="col-6 px-2">
      <div class="d-flex align-items-center justify-content-end">
        <div class="mt-2">
          <a href="#" class="text-decoration-none text-muted">
            <%= image_tag("notification-icon.svg", :alt => "notification-icon", :class => "mb-2") %>
          </a>
        </div>

        <span class="vertical-divider px-4">|</span>

        <div class="mt-2">
          <a href="#" class="text-decoration-none text-muted">
            <%= image_tag("user-icon.svg", :alt => "user-icon", :class => "mb-2") %>
          </a>
        </div>

        <span class="vertical-divider px-4">|</span>

        <div class="mt-2">
          <% country = Country.find(current_user.last_connected_country.to_i) %>
          <%= image_tag(country.icon, style: 'height:35px; width:35px;', :alt => "cr-flag-icon", :class => "mb-2") %>
        </div>
      </div>
    </div>
  </div>
</nav>

<%= render "/shared/sidebar" %>

app/views/shared/_sidebar.html.erb
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header bg-sidebar">
    <%= image_tag("logo-sidebar.svg", :alt => "logo-sidebar", :width => "95%", :class => "py-2 px-5 offcanvas-title", :id => "offcanvasExampleLabel") %>
    <button type="button" class="btn-close text-reset text-light" data-bs-dismiss="offcanvas" aria-label="Close" style="margin-right: 2rem;"></button>
  </div>
  <div class="offcanvas-body bg-sidebar">
    <div class="dropdown mt-3 text-light">
      <ul class="navbar-nav mr-auto" style="margin-left:4.5rem;">
        <li class="nav-item active mb-5">
          <%= link_to main_home_path do %>
            <%= image_tag("sidebar-inicio.svg", :alt => "user-icon", :class => "mb-2") %>
          <% end %>
        </li>
        <li class="nav-item active mb-5">
          <%= link_to products_path do %>
            <%= image_tag("sidebar-productos.svg", :alt => "user-icon", :class => "mb-2") %>
          <% end %>
        </li>
        <li class="nav-item active mb-5">
          <%= link_to routes_path do %>
            <%= image_tag("sidebar-rutas.svg", :alt => "user-icon", :class => "mb-2") %>
          <% end %>
        </li>
        <li class="nav-item active mb-5">
          <%= link_to new_user_registration_path do %>
            <%= image_tag("sidebar-ajustes.svg", :alt => "user-icon", :class => "mb-2") %>
          <% end %>
        </li>
        <li class="nav-item active mb-5">
          <%= link_to main_about_path do %>
            <%= image_tag("sidebar-nosotros.svg", :alt => "user-icon", :class => "mb-2") %>
          <% end %>
        </li>
        <li class="nav-item active mb-5">
          <%= button_to destroy_user_session_path, :method => "delete", data: { 'turbo-method': :delete, 'turbo-confirm': '¿Estás seguro(a) que deseas salir?' }, :class => "btn" do %>
            <%= image_tag("sidebar-salir.svg", :alt => "user-icon", :class => "mb-2") %>
          <% end %>
        </li>
      </ul>
      <div class="text-center mt-5">
        <%= image_tag("app-version.svg", :alt => "user-icon", :class => "mb-2") %>
      </div>
    </div>
  </div>
</div>