config/routes.rb
Rails.application.routes.draw do
  resources :batches
  resources :products
  resources :operations
  resources :routes
  resources :countries
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'main/home', to: 'home#main', as: 'main_home'
  get 'main/about', to: 'home#about', as: 'main_about'

  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :country
  has_many :operations

  validates :description, presence: true
  validates :code, presence: true, uniqueness: true
  validates :country_id, presence: true
  validate :has_one_operation_at_least, :on => :create

  def products
    products = []
    operations.each do |operation|
      operation.batches.each do |batch|
        products << batch.product
      end
    end
    products = products.uniq
  end

  def has_one_operation_at_least
    if operations.empty?
      errors.add(:operations, "Route must have at least one operation")
    end
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  attr_accessor :route
  before_action :set_route, only: %i[ show edit update destroy ]
  before_action :set_operations, only: %i[ new edit create update ]
  before_action :set_countries, only: %i[ new edit update create ]
  before_action :set_products, only: %i[ new edit update create ]

  # GET /routes or /routes.json
  def index
    @routes = Route.where(country_id: set_country_id)
    @routes_length = Route.where(country_id: set_country_id).length
    if @routes.nil? || @routes.empty?
      @routes = []
    else
      @routes = @routes.paginate(page: params[:page], per_page: 6)
    end
  end

  # GET /routes/1 or /routes/1.json
  def show
    unless @route.products.empty?
      products_length = @route.products.length
      @products = @route.products.paginate(page: params[:page], per_page: 2)
    else
      @products = []
    end
    operations_length = @route.operations.length
    @operations = @route.operations.paginate(page: params[:page], per_page: 2)
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes or /routes.json
  def create
    set_operations_to_be_added
    @route = Route.new(route_params)
    @route.code = "code" + Random.random_number(1000).to_s
    @route.country_id = set_country_id
    unless @operations_to_be_added.empty?
      @operations_to_be_added.each do |operation|
        operation.route_id = @route.id
        operation.save
        @route.operations << operation
      end
    end
    create_route_code
    respond_to do |format|
      if @route.save
        format.html { redirect_to route_url(@route), notice: "Route was successfully created." }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1 or /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to route_url(@route), notice: "Route was successfully updated." }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1 or /routes/1.json
  def destroy
    @route.destroy

    respond_to do |format|
      format.html { redirect_to routes_url, notice: "Route was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_route
    @route = Route.find(params[:id])
  end

  def set_countries
    @countries = Country.all
  end

  def set_country_id
    @country_id = current_user.last_connected_country
  end

  def set_operations
    @operations = Operation.where(country_id: set_country_id, route_id: nil)
  end

  def set_products
    @products = Product.all
  end

  def create_route_code
    product = Product.find(params[:route][:product_id].to_i)
    @route.code = @route.country.code + product.code + @operations_to_be_added.length.to_s
  end

  def set_operations_to_be_added
    @operations_to_be_added = []
    operations = params[:selected_operations]
    unless operations.nil?
      operations.each do |operation|
        @operations_to_be_added << Operation.find(operation.to_i)
      end
    end
  end

  # Only allow a list of trusted parameters through.
  def route_params
    params.require(:route).permit(:description, :country_id)
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_with(model: route) do |form| %>
  <%= render 'shared/errors', obj: @route %>

  <div class="mb-4">
    <%= form.label "Producto", style: "display: block" %>
    <%= form.select :product_id, options_for_select(@products.collect { |p| [p.code, p.id] }), {}, class: "form-select" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mt-4">
    <table class="table table-hover ">
      <thead>
      <tr>
        <th class="text-center" scope="col">Operación</th>
        <th class="text-center" scope="col">Agregar operación</th>
      </tr>
      </thead>
      <tbody>
      <% if @operations.empty? %>
        <tr>
          <td colspan="2" class="text-center">No hay operaciones...<a href="<%= new_operation_path %>"><i>Agregar
            operación</i></a></td>
        </tr>
      <% else %>
        <% @operations.each do |operation| %>
          <% if operation.route_id.nil? %>
            <%= render "/routes/operations_table/table_column", operation: operation %>
          <% end %>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>

  <% unless @operations.empty? %>
    <div class="d-flex mt-5 align-items-center justify-content-end">
      <%= link_to "Regresar", routes_path, class: "btn-secundario" %>&nbsp;&nbsp;
      <%= form.submit "Crear Ruta", class: "btn-primario" %>
    </div>
  <% else %>
    <div class="d-flex mt-5 align-items-center justify-content-end">
      <%= link_to "Regresar", routes_path, class: "btn-secundario" %>&nbsp;&nbsp;
    </div>
  <% end %>

<% end %>

app/views/routes/_route.html.erb
<div id="<%= dom_id route %>">

  <div class="d-flex align-items-center responsive-width">
    <table class="table table-bordered text-center responsive-width shadow-sm">
      <tr class="table-head-background">
        <th>Nombre de la ruta</th>
        <th>N. de productos asociados</th>
        <th>N. de operaciones</th>
      </tr>
      <tr class="table-row-background">
        <td style="width: 20%; padding: 1rem;"><%= route.code %></td>
        <td style="width: 40%; padding: 1rem;"><%= route.products.count %></td>
        <td style="width: 40%; padding: 1rem;"><%= route.operations.count %></td>
      </tr>
    </table>
  </div>

  <div class="mt-3">
    <%= image_tag("horizontal-divider.svg", :alt => "horizontal-divider", :width => "97%", :class => "mb-3") %>
  </div>

  <%# -- resultados de busqueda -- %>
  <div class="d-flex align-items-center justify-content-center mt-5 responsive-width">
    <div class="col-6">
      <%= image_tag("routes-operations-headline.svg", :alt => "routesDetails-title", :width => "20%", :class => "mb-3") %>
    </div>
    <div class="col-6 container text-end">
      <%= link_to new_operation_path, class: "btn-agregar" do %>
        <i class="bi bi-plus-circle"></i>&nbsp;&nbsp;Agregar operación
      <% end %>
    </div>
  </div>
  <%# ------------- %>

  <div class="d-flex mt-4 align-items-center responsive-width">
    <table class="table table-bordered text-center responsive-width shadow-sm">
      <tr class="table-head-background">
        <th>Número de operación</th>
        <th>Encargado</th>
        <th>N° Lotes</th>
        <th>Acciones</th>
      </tr>

      <% @operations.each do |operation| %>
        <tr class="table-row-background">
          <td style="width: 25%; padding: 1rem;"><%= operation.code %></td>
          <td style="width: 25%; padding: 1rem;">Alina Rodríguez</td>
          <td style="width: 25%; padding: 1rem;"><%= operation.batches.count %></td>
          <td style="width: 25%; padding: 1rem;">
            <%= link_to "Detalles", operation_path(operation), class: "btn-ver" %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <%# -- paginacion -- %>
  <div class="flickr_pagination mt-5 mb-3 responsive-width">
    <%= will_paginate @operations, :container => false %>
  </div>
  <%# ------------- %>

  <div class="mt-2">
    <%= image_tag("horizontal-divider.svg", :alt => "horizontal-divider", :width => "97%", :class => "mb-3") %>
  </div>

  <%# -- resultados de busqueda -- %>
  <div class="d-flex align-items-center justify-content-center mt-5">
    <%# <div class="col-4">
      <%=image_tag("routes-products-headline.svg", :alt => "routesDetails-title", :width => "20%",  :class => "mb-3") %>
    <%# </div> %>
    <div class="col-6">
      <p><%= @route.products.count %> Resultados</p>
    </div>
    <div class="col-6 container text-end">
      <%= image_tag("search-tools.svg", :alt => "search-tools", :width => "80%", :class => "mb-3", :style => "margin-right: 5%;") %>
    </div>
  </div>
  <%# ------------- %>

  <div class="d-flex mt-3 align-items-center responsive-width">
    <table class="table table-bordered text-center responsive-width shadow-sm">
      <tr class="table-head-background">
        <th>Código del producto</th>
        <th>Descripción</th>
        <th>Acciones</th>
      </tr>

      <% @products.each do |product| %>
        <tr class="table-row-background">
          <td style="width: 25%; padding: 1rem;"><%= product.code %></td>
          <td style="width: 50%; padding: 1rem;"><%= product.description %></td>
          <td style="width: 25%; padding: 1rem;">
            <%= link_to "Detalles", product_path(product), class: "btn-ver" %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <%# -- paginacion -- %>
  <div class="flickr_pagination my-5 responsive-width">
    <% unless @products.empty? || @products.nil? %>
      <%= will_paginate @products, :container => false %>
    <% end %>
  </div>
  <%# ------------- %>

</div>

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render "form", route: @route %>

<br>

<div>
  <%= link_to "Show this route", @route %> |
  <%= link_to "Back to routes", routes_path %>
</div>

app/views/routes/index.html.erb
<%= render "/shared/navbar" %>

<div class="h-100 w-100 secondary-background">
  <div class="container mt-5">
    <div class="container mt-4 mx-auto">
      <div style="width: 95%;">
        <%= render "/shared/messages" %>
      </div>
    </div>

    <%# -- Titulo de ruta y boton de agregar -- %>
    <div>
      <%= image_tag("Routes-title.svg", :alt => "routes-title", :width => "83%", :class => "mb-3") %>

      &nbsp;&nbsp;&nbsp;

      <%= link_to new_route_path, class: "btn-agregar" do %>
        <i class="bi bi-plus-circle"></i>&nbsp;&nbsp;Agregar ruta
      <% end %>
    </div>
    <%# ------------- %>

    <%# -- resultados de busqueda -- %>
    <div class="d-flex align-items-center justify-content-center mt-5">
      <div class="col-6">
        <p><%= @routes_length %> Resultados</p>
      </div>
      <div class="col-6 container text-end">
        <%= image_tag("search-tools.svg", :alt => "search-tools", :width => "80%", :class => "mb-3", :style => "margin-right: 5%;") %>
      </div>
    </div>
    <%# ------------- %>

    <%# -- tabla de rutas -- %>
    <div id="routes" class="responsive-width mt-4">
      <table class="table table-bordered text-center shadow-sm">
        <tr class="table-head-background">
          <th>Nombre de la ruta</th>
          <th>N° Productos</th>
          <th>N° Operaciones</th>
          <th>Acciones</th>
        </tr>

        <% @routes.each do |route| %>
          <tr class="table-row-background">
            <td style="width: 30%; padding: 1.2rem;"><%= route.code %></td>
            <td style="width: 15%; padding: 1.2rem;"><%= route.products.count %></td>
            <td style="width: 15%; padding: 1.2rem;"><%= route.operations.count %></td>
            <td style="width: 40%; padding: 1.2rem;">
              <%= link_to "Detalles", route_path(route), class: "btn-ver", route: route %>
              <%= link_to "Eliminar", route_path(route), data: { 'turbo-method': :delete, 'turbo-confirm': '¿Estás seguro(a) que deseas eliminar esta ruta?' }, class: "btn-eliminar" %>
            </td>
          </tr>
        <% end %>
      </table>

      <%# -- paginacion -- %>
      <% unless @routes.empty? || @routes.nil? %>
        <div class="flickr_pagination my-5 responsive-width">
          <%= will_paginate @routes, :container => false %>
        </div>
      <% end %>
      <%# ------------- %>

    </div>
    <%# ------------- %>


  </div>

</div>

app/views/routes/new.html.erb
<%= render "/shared/navbar" %>

<div>
  <div class="container mt-5">
    <%= image_tag("new-route-headline.svg", :alt => "new-route-title", :width => "97%", :class => "mb-3") %>

    <%= render "form", route: @route %>

    <br>
  </div>

</div>

app/views/routes/show.html.erb
<%= render "/shared/navbar" %>

<div class="h-100 w-100 secondary-background">
  <div class="container mt-5">
    <div class="container mt-4 mx-auto">
      <div style="width: 95%;">
        <%= render "/shared/messages" %>
      </div>
    </div>

    <%# -- Titulo de ruta y boton de eliminar -- %>
    <div>
      <%= image_tag("route-details-headline.svg", :alt => "routesDetails-title", :width => "83%", :class => "mb-3") %>

      &nbsp;&nbsp;&nbsp;

      <%= link_to "#", class: "btn-eliminar" do %>
        <i class="bi bi-plus-circle"></i>&nbsp;&nbsp;Eliminar ruta
      <% end %>
    </div>
    <%# ------------- %>

    <div class="mt-4 mb-5">
      <%= render @route %>
    </div>

    <div class="d-flex mt-5 pb-5 align-items-center justify-content-end" style="margin-right: 4%;">
      <%= link_to "Regresar", routes_path, class: "btn-secundario" %>
    </div>
  </div>
</div>