config/routes.rb
Rails.application.routes.draw do
  resources :batches
  resources :products
  resources :operations
  resources :routes
  resources :countries
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'main/home', to: 'home#main', as: 'main_home'
  get 'main/about', to: 'home#about', as: 'main_about'

  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/product.rb
class Product < ApplicationRecord
  validates :description, presence: true
  validates :code, presence: true, uniqueness: true, length: { maximum: 2 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :cost, presence: true, numericality: { greater_than: 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products_length = Product.all.length
    @products = Product.paginate(page: params[:page], per_page: 6)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:description, :price, :cost, :code)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="responsive-width">
  <%= form_with(model: product) do |form| %>
    <%= render 'shared/errors', obj: @product %>

    <div class="d-flex mt-5">
      <div class="col-6">
        <div>
          <%= form.label "Código", style: "display: block" %>
          <%= form.text_field :code, style: "display: block", class: "form-control" %>
        </div>

        <br>

        <div>
          <%= form.label "Precio de unidad", style: "display: block" %>
          <%= form.text_field :price, class: "form-control", placeholder: "$" %>
        </div>

        <br>

        <div>
          <%= form.label "Costo de producción", style: "display: block" %>
          <%= form.text_field :cost, class: "form-control", placeholder: "$" %>
        </div>
      </div>

      <div class="col-6 mx-2">
        <%= form.label "Descripción", style: "display: block" %>
        <%= form.text_area :description, class: "form-control mt-1", rows: "8" %>
      </div>
    </div>

    <div class="d-flex mt-5 align-items-center justify-content-end">
      <%= link_to "Regresar", products_path, class: "btn-secundario" %>&nbsp;&nbsp;
      <%= form.submit "Crear producto", class: "btn-primario" %>
    </div>
  <% end %>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <div class="d-flex align-items-center responsive-width">
    <div class="col-10">
      <table class="table table-bordered text-center responsive-width shadow-sm">
        <tr class="table-head-background">
          <th>Código del modelo</th>
          <th>Descripción</th>
        </tr>
        <tr class="table-row-background">
          <td style="width: 20%; padding: 2rem;"><%= product.code %></td>
          <td style="width: 80%; padding: 2rem;"><%= product.description %></td>
        </tr>
      </table>
    </div>

    <div class="col-2 text-center">
      <%= image_tag("product-image.svg", :alt => "product-image", :class => "mb-3") %>
    </div>
  </div>

  <div class="mt-3">
    <%= image_tag("horizontal-divider.svg", :alt => "horizontal-divider", :width => "95%", :class => "mb-3") %>
  </div>

  <div class="d-flex mt-3 align-items-center">
    <div class="col-4 pt-2">
      <div clas="mb-5">
        <table class="table table-bordered text-center shadow-sm">
          <tr class="table-head-background">
            <th>Ruta asociada</th>
          </tr>
          <tr class="table-row-background">
            <td style="width: 20%; padding: 1rem;">Ruta 1</td>
          </tr>
        </table>
      </div>

      <div class="mt-4 pt-2">
        <table class="table table-bordered text-center shadow-sm">
          <tr class="table-row-background">
            <th style="padding: 1rem;">Valor de venta</th>
            <td style="padding: 1rem;">$ <%= product.price %></td>
          </tr>
        </table>
      </div>

      <div class="mt-4 pt-2">
        <table class="table table-bordered text-center shadow-sm">
          <tr class="table-row-background">
            <th style="width: 58%; padding: 1rem;">Costo de producción</th>
            <td style="width: 42%; padding: 1rem;">$ <%= product.cost %></td>
          </tr>
        </table>
      </div>
    </div>

    <div class="col-8 mx-4">
      <%= image_tag("graph-pic.png", :alt => "graph-pic", :width => "90%", :height => "80%", :class => "mb-3 shadow-sm border rounded-2") %>
    </div>
  </div>

  <div class="d-flex mt-5 align-items-center justify-content-end" style="margin-right: 5%;">
    <%= link_to "Regresar", products_path, class: "btn-secundario" %>
  </div>
</div>

app/views/products/edit.html.erb
<%= render "/shared/navbar" %>

<div>
  <div class="container mt-5">
    <%= image_tag("edit-product-headline.svg", :alt => "products-title", :width => "97%", :class => "mb-3") %>

    <%= render "form", product: @product %>

    <br>
  </div>
</div>

app/views/products/index.html.erb
<%= render "/shared/navbar" %>

<div class="h-100 w-100 secondary-background">
  <div class="container mt-5">
    <div class="container mt-4 mx-auto">
      <div style="width: 95%;">
        <%= render "/shared/messages" %>
      </div>
    </div>

    <%# -- Titulo de productos y boton de agregar -- %>
    <div>
      <%= image_tag("Products-title.svg", :alt => "products-title", :width => "80%", :class => "mb-3") %>

      &nbsp;&nbsp;&nbsp;

      <%= link_to new_product_path, class: "btn-agregar" do %>
        <i class="bi bi-plus-circle"></i>&nbsp;&nbsp;Agregar producto
      <% end %>
    </div>
    <%# ------------- %>

    <%# -- resultados de busqueda -- %>
    <div class="d-flex align-items-center justify-content-center mt-5">
      <div class="col-6">
        <p><%= @products_length %> Resultados</p>
      </div>
      <div class="col-6 container text-end">
        <%= image_tag("search-tools.svg", :alt => "search-tools", :width => "80%", :class => "mb-3", :style => "margin-right: 5%;") %>
      </div>
    </div>
    <%# ------------- %>

    <%# -- tabla de productos -- %>
    <div id="products" class="responsive-width mt-4">
      <table class="table table-bordered text-center shadow-sm">
        <tr class="table-head-background">
          <th>Código del modelo</th>
          <th>Descripción</th>
          <th>Acciones</th>
        </tr>

        <% @products.each do |product| %>
          <tr class="table-row-background">
            <td style="width: 20%; padding: 1.2rem;"><%= product.code %></td>
            <td style="width: 40%; padding: 1.2rem;"><%= product.description %></td>
            <td style="width: 40%; padding: 1.2rem;">
              <%= link_to "Detalles", product_path(product), class: "btn-ver" %>
              <%= link_to "Modificar", edit_product_path(product), class: "btn-modificar" %>
              <%= link_to "Eliminar", product_path(product), data: { 'turbo-method': :delete, 'turbo-confirm': '¿Estás seguro(a) que deseas eliminar este producto?' }, class: "btn-eliminar" %>
            </td>
          </tr>
        <% end %>
      </table>

      <%# -- paginacion -- %>
      <div class="flickr_pagination my-5 responsive-width">
        <%= will_paginate @products, :container => false %>
      </div>
      <%# ------------- %>

    </div>
    <%# ------------- %>
  </div>
</div>

app/views/products/new.html.erb
<%= render "/shared/navbar" %>

<div>
  <div class="container mt-5">
    <%= image_tag("new-product-headline.svg", :alt => "products-title", :width => "97%", :class => "mb-3") %>

    <%= render "form", product: @product %>

    <br>
  </div>
</div>

app/views/products/show.html.erb
<%= render "/shared/navbar" %>

<div class="h-100 w-100 secondary-background">
  <div class="container mt-5">
    <div class="container mt-4 mx-auto">
      <div style="width: 95%;">
        <%= render "/shared/messages" %>
      </div>
    </div>

    <%# -- Titulo de productos y boton de agregar -- %>
    <div>
      <%= image_tag("details-product-headline.svg", :alt => "details-products-title", :width => "95%", :class => "mb-3") %>
    </div>
    <%# ------------- %>

    <%= render @product %>
  </div>
</div>