config/routes.rb
Rails.application.routes.draw do
  resources :batches
  resources :products
  resources :operations
  resources :routes
  resources :countries
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'main/home', to: 'home#main', as: 'main_home'
  get 'main/about', to: 'home#about', as: 'main_about'

  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/operation.rb
class Operation < ApplicationRecord
  #belongs_to :route
  has_many :batches

  validates :description, presence: true
  validates :code, presence: true, uniqueness: true, length: { maximum: 4, minimum: 4 }
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[ show edit update destroy ]

  # GET /operations or /operations.json
  def index
    @operations_length = Operation.all.length
    @operations = Operation.paginate(page: params[:page], per_page: 6)

  end

  # GET /operations/1 or /operations/1.json
  def show
    @batches_length = @operation.batches.length
    @batches = @operation.batches.paginate(page: params[:page], per_page: 2)
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations or /operations.json
  def create
    #byebug
    @operation = Operation.new(operation_params)
    @operation.country_id = set_country_id
    respond_to do |format|
      if @operation.save
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully created." }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully updated." }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: "Operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_operation
    @operation = Operation.find(params[:id])
  end

  def set_country_id
    @country_id = current_user.last_connected_country
  end

  # Only allow a list of trusted parameters through.
  def operation_params
    params.require(:operation).permit(:description, :route_id, :code)
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_with(model: operation) do |form| %>
  <%= render 'shared/errors', obj: @operation %>

  <div class="d-flex mt-5 align-items-center">

    <div class="col-6">
      <div>
        <%= form.label "Código", style: "display: block" %>
        <%= form.text_field :code, style: "display: block", class: "form-control mt-1" %>
      </div>
    </div>

    <div class="col-6 mx-2">
      <%= form.label "Descripción", style: "display: block" %>
      <%= form.text_field :description, class: "form-control mt-1", rows: "8" %>
    </div>
  </div>


  <div class="d-flex mt-5 align-items-center justify-content-end">
    <%= link_to "Regresar", :back, class: "btn-secundario" %>&nbsp;&nbsp;
    <%= form.submit "Crear operación", class: "btn-primario" %>
  </div>
<% end %>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>">
  <div class="d-flex align-items-center responsive-width">
    <div class="col-12">
      <table class="table table-bordered text-center responsive-width shadow-sm">
        <tr class="table-head-background">
          <th>Código de la operación</th>
          <th>Descripción</th>
          <th>Nª Lotes asociados</th>
        </tr>
        <tr class="table-row-background">
          <td style="width: 25%; padding: 1.2rem;"><%= operation.code %></td>
          <td style="width: 50%; padding: 1.2rem;"><%= operation.description %></td>
          <td style="width: 25%; padding: 1.2rem;"><%= operation.batches.count %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="mt-3">
    <%= image_tag("horizontal-divider.svg", :alt => "horizontal-divider", :width => "97%", :class => "mb-3") %>
  </div>

  <div class="d-flex align-items-center justify-content-center mt-4 responsive-width">
    <div class="col-6">
      <%= image_tag("personal-encargado.svg", :alt => "routesDetails-title", :class => "mb-3") %>
    </div>
    <div class="col-6 container text-end">
      <%= link_to "#", class: "btn-agregar" do %>
        <i class="bi bi-plus-circle"></i>&nbsp;&nbsp;Asignar personal
      <% end %>
    </div>
  </div>

  <div class="d-flex mt-3 align-items-center responsive-width ">
    <table class="table table-bordered text-center responsive-width shadow-sm">
      <tr class="table-head-background">
        <th>Nombre completo</th>
        <th>Cargo</th>
        <th>Acciones</th>
      </tr>

      <tr class="table-row-background">
        <td style="width: 25%; padding: 1rem;">Alina Rodríguez</td>
        <td style="width: 25%; padding: 1rem;">Ingeniera en planta</td>
        <td style="width: 25%; padding: 1rem;">
          <%= link_to "Detalles", "#", class: "btn-ver" %>
          <%= link_to "Desasignar", "#", class: "btn-eliminar" %>
        </td>
      </tr>
    </table>
  </div>

  <div class="mt-5">
    <%= image_tag("horizontal-divider.svg", :alt => "horizontal-divider", :width => "97%", :class => "mb-3") %>
  </div>

  <div class="d-flex align-items-center justify-content-center mt-4 responsive-width">
    <div class="col-6">
      <%= image_tag("lotes-asociados.svg", :alt => "routesDetails-title", :class => "mb-3") %>
    </div>
    <div class="col-6 container text-end">
      <%= link_to new_batch_path, class: "btn-agregar" do %>
        <i class="bi bi-plus-circle"></i>&nbsp;&nbsp;Agregar lote
      <% end %>
    </div>
  </div>

  <div class="d-flex align-items-center responsive-width mt-3">
    <div class="col-12">
      <table class="table table-bordered text-center responsive-width shadow-sm">
        <tr class="table-head-background">
          <th>Código de lote</th>
          <th>Unidades asociadas</th>
          <th>Estado</th>
          <th>Acciones</th>
        </tr>
        <% @batches.each do |batch| %>
          <tr class="table-row-background">
            <td style="width: 23%; padding: 1.2rem;"><%= batch.code %></td>
            <td style="width: 23%; padding: 1.2rem;"><%= batch.units %></td>
            <td style="width: 23%; padding: 1.2rem;"><%= batch.current_operation %></td>
            <td style="width: 31%; padding: 1.2rem;">
              <%= link_to "Detalles", batch_path(batch), class: "btn-ver" %>
              <%= link_to "Modificar", "#", class: "btn-modificar" %>
              <%= link_to "Eliminar", batch_path(batch), data: { 'turbo-method': :delete, 'turbo-confirm': '¿Estás seguro(a) que deseas eliminar este lote?' }, class: "btn-eliminar" %>
            </td>
          </tr>
        <% end %>
      </table>

      <%# -- paginacion -- %>
      <% unless @batches.empty? || @batches.nil? %>
        <div class="flickr_pagination my-5 responsive-width">
          <%= will_paginate @batches, :container => false %>
        </div>
      <% end %>
      <%# ------------- %>
    </div>
  </div>
</div>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Show this operation", @operation %> |
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/index.html.erb
<div class="container mt-4 mx-auto">
  <div style="width: 95%;">
    <%= render "/shared/messages" %>
  </div>
</div>

<h1>Operations</h1>

<div id="operations">
  <% @operations.each do |operation| %>
    <%= operation.code %>
    <p>
      <%= link_to "Show this operation", operation %>
    </p>
  <% end %>
</div>

<%= link_to "New operation", new_operation_path %>

app/views/operations/new.html.erb
<%= render "/shared/navbar" %>

<div>
  <div class="container mt-5">
    <%= image_tag("new-operation-headline.svg", :alt => "new-operation-headline", :width => "97%", :class => "mb-3") %>

    <%= render "form", operation: @operation %>

    <br>
  </div>
</div>

app/views/operations/show.html.erb
<%= render "/shared/navbar" %>

<div class="h-100 w-100 secondary-background">
  <div class="container mt-5">
    <div class="container mt-4 mx-auto">
      <div style="width: 95%;">
        <%= render "/shared/messages" %>
      </div>
    </div>

    <%# -- Titulo de operación -- %>
    <div class="">
      <%= image_tag("operation-details-headline.svg", :alt => "details-operation-title", :width => "96%", :class => "mb-5") %>
    </div>
    <%# ------------- %>

    <%= render @operation %>

    <div class="d-flex mt-3 pb-5 align-items-center justify-content-end" style="margin-right: 4%;">
      <%= link_to "Regresar", :back, class: "btn-secundario" %>
    </div>
  </div>
</div>